#! /usr/bin/env python
"""Create Wireguard Keys."""

import os
import sys
from pathlib import Path
from subprocess import check_output

from src.arguments import get_keys_argparser

if __name__ == "__main__":
    parser = get_keys_argparser(__doc__)
    args = parser.parse_args()

    pk: Path = args.key_dir / args.private_key_file
    try:
        if not args.dry_run and not os.access(pk if pk.exists() else pk.parent, os.W_OK):
            raise PermissionError()
    except PermissionError:
        print("Key file", pk, "is not writable, exiting.", file=sys.stderr)
        sys.exit(os.EX_NOPERM)

    priv_key = check_output(["wg", "genkey"])
    if args.verbose:
        print("Writing", pk)
    if args.dry_run:
        print("Private key:", priv_key)
    else:
        pk.write_bytes(priv_key)
    pk = pk.with_suffix(".pub")
    public_key = check_output(["wg", "pubkey"], input=priv_key)
    if args.verbose:
        print("Writing", pk)
    if args.dry_run:
        print("Public key:", public_key)
    else:
        pk.write_bytes(public_key)
