#! /usr/bin/env python
"""Configure Wireguard interfaces."""

import sys
from contextlib import nullcontext
from pathlib import Path

from src.arguments import DEFAULT_ADDR, get_netdev_argparser
from src.systemd_config.caseless_dict import CaselessDict
from src.systemd_config.reader import parse
from src.systemd_config.writer import dump


def _config_action_msg(exists: bool, ignored: bool) -> str:
    action = "recreating" if ignored else "loading"
    return "exist, " + action if exists else "does not exist, creating"


if __name__ == "__main__":
    parser = get_netdev_argparser(__doc__)
    args = parser.parse_args()

    netdev_fn: str = args.networkd_config_prefix + ".netdev"
    netdev_file: Path = args.networkd_config_dir / netdev_fn
    network_fn: str = args.networkd_config_prefix + ".network"
    network_file: Path = args.networkd_config_dir / network_fn

    if args.verbose:
        print(
            netdev_fn,
            _config_action_msg(netdev_file.exists(), args.force_new),
            file=sys.stderr,
        )
        print(
            network_fn,
            _config_action_msg(network_file.exists(), args.force_new),
            file=sys.stderr,
        )

    if netdev_file.exists() and not args.force_new:
        with netdev_file.open() as fp:
            netdev_config, netdev_comments = parse(fp, preserve_comments=True)
        print(netdev_config)
    else:
        netdev_config = CaselessDict()
        netdev_comments = {}

    # section names are case-sensitive, ensure proper names
    for section in ("WireGuard", "NetDev"):
        if section in netdev_config and section not in set(netdev_config.keys()):
            netdev_config.rename(section, section)

    netdev_section = netdev_config.setdefault("NetDev", CaselessDict())
    netdev_section["Name"] = args.interface
    netdev_section["Kind"] = "wireguard"
    netdev_section["Description"] = args.description

    netdev_section = netdev_config.setdefault("WireGuard", CaselessDict())
    if "listen_port" in args:
        netdev_section["ListenPort"] = args.listen_port
    netdev_config.setdefault("WireGuard", CaselessDict())["PrivateKeyFile"] = (
        args.key_dir / args.private_key_file
    )

    if args.dry_run:
        print("#", netdev_fn)
        context_manager = nullcontext(sys.stdout)
    else:
        context_manager = netdev_file.open("w")

    with context_manager as fp:
        dump(fp, netdev_config, netdev_comments)
    if args.verbose and not args.dry_run:
        print(netdev_fn, "saved")

    if network_file.exists() and not args.force_new:
        with network_file.open() as fp:
            network_config, network_comments = parse(fp, preserve_comments=True)
    else:
        network_config = CaselessDict()
        network_comments = {}

    # section names are case-sensitive, ensure proper names
    for section in ("Match", "Network"):
        if section in network_config and section not in set(network_config.keys()):
            network_config.rename(section, section)

    network_section = network_config.setdefault("Match", CaselessDict())
    network_section["Name"] = args.interface
    network_section["Kind"] = "wireguard"

    network_section = network_config.setdefault("Network", CaselessDict())
    network_section["Description"] = args.description
    network_section["Address"] = args.network or DEFAULT_ADDR
    if "dns" in args and args.dns:
        network_section["DNS"] = args.dns
    network_section["IPMasquerade"] = args.ip_masquerade

    if args.dry_run:
        print("#", network_fn)
        context_manager = nullcontext(sys.stdout)
    else:
        context_manager = network_file.open("w")

    with context_manager as fp:
        dump(fp, network_config, network_comments)
    if args.verbose and not args.dry_run:
        print(network_fn, "saved")
